### ISSUE TITLE
vcx cloud agency has port conflicts with orb

### ISSUE THREAD

**Issue by Moopli** [ianco/aries-agent-test-harness#365]
It would be best if optional services didn't have port conflicts, so they can be run together in whatever combination is needed for a test.

In general (if possible) it would be useful to have services use contiguous port ranges so it's easier to verify that there are no conflicts, just for convenience.

**Comment by nodlesh** [comment]
There should be no port conflicts as of a merge yesterday. Are you still seeing them?

**Comment by swcurran** [comment]
Perhaps we need a "SERVICES.md" document that says what services and ports are being used, and a reference to that from the "How to Build a Backchannel" document.  Might prevent such issues in the future.

**Comment by nodlesh** [comment]
Yes, that is a good idea.
