### ISSUE TITLE
Aries Framework JavaScript tests not running locally

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#388]
I can't get AFJ tests run locally anymore. I'm trying to run the same set of tests as in the nightly runs.  Here's what I'm doing:

- using main
- rebuild acapy-main and javascript
- execute: `./manage run -d acapy-main -a javascript -t @AcceptanceTest -t @AIP10 -t ~@wip`
- After the start up process completes properly, the second step of each test stops with this error:

` Assertion Failed: resp_status 500 is not 200; {"name":"TypeError","message":"class_transformer_1.plainToClass is not a function","status":500,"errors":[],"stack":"TypeError: class_transformer_1.plainToClass is not a function\n    at Function.fromJSON (/src/node_modules/@aries-framework/core/src/utils/JsonTransformer.ts:12:12)\n    at ConnectionController.<anonymous> (/src/src/controllers/ConnectionController.ts:73:23)\n    at Generator.next (<anonymous>)\n    at /src/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/src/node_modules/tslib/tslib.js:113:16)\n    at ConnectionController.$ctx [as receiveInvitation] (/src/src/controllers/ConnectionController.ts:44:24)\n    at /src/node_modules/@tsed/platform-params/src/builder/PlatformParams.ts:88:39\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}`

Any ideas?  @TimoGlastra

**Comment by TimoGlastra** [comment]
Should be fixed once this PR is merged and released: https://github.com/hyperledger/aries-framework-javascript/pull/547
