### ISSUE TITLE
Some steps take a long time to run

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#389]
Some of the Test Harness steps take a long time to run -- much longer than I would expect.  [Attached](https://docs.google.com/spreadsheets/d/1B1t4XElAcKv_sj2C1wPTl_STa05x6O1CiKHjAJ9jbw4/edit?usp=sharing) is a sorted list of the times taken per step in a multi-feature test run (all tagged `AIP10` tests, minus `wip`).  It would be nice to investigate two of the steps:

- `And "Bob" has an issued credential from Acme with Data_DL_MaxValues # features/steps/0037-present-proof.py:7 39.165s`
   - Each instance of this "has an issued credential..." took a long time from 6 to 39 seconds. Could be that it includes the creation of the cred def.  But worth a bit of a look
- `And "Faber" and "Bob" have an existing connection  # features/steps/0160-connection.py:273 10.496s`
  - Each instance of these took 10.49 secs - adding about 3 minutes to a 9 minute run.  Not sure why this should take any time at all.

It would be great if someone could take a peek at these and see if they can be sped up.

**Comment by ianco** [comment]
The connection scenario had a long `sleep()` step, I've shortened it here:  https://github.com/hyperledger/aries-agent-test-harness/pull/390

The credential issue time seems mainly due to the time required to create the cred def.

**Comment by nodlesh** [comment]
I think the long sleep was to account for another framework to get along in the process. The removal of the interim state checks is what is causing the need for the waits.  If you shortened the sleep, I'd expect something in a different runset to fail. Hoping it doesn't, but that is my expectation.
