### ISSUE TITLE
Latest image of python:3-7.slim breaks the build of aca-py

### ISSUE THREAD

**Issue by pruneau628** [ianco/aries-agent-test-harness#454]
While trying to implement some ci around AATH, we noticed that `./managed rebuild -a acapy` is broken:
the error message while rebuilding can be found below (see Build Error at end of this post)

We tracked the problem to a change in the base container, referred to in `aries-agent-test-harness/aries-backchannels/acapy/Dockerfile.acapy` first line `FROM python:3.7-slim`

From this commit: https://github.com/docker-library/python/commit/a9815ead3ae016edf7039285cb267b14a5700169 
We can see that the `python:3.7-slim` image had the following version upgrades recently.
- Python from version `3.7.12` to `3.7.13`
- pip from version `21.2.4` to `22.0.4`

If you have a local images, this can be also figured out with `docker history --no-trunc python:3.7-slim` (warning, long lines output). As of today 2022, the image that breaks the build shows that its layers where created `5 days ago`, whereas the one that works show `2 weeks ago`.

The errors happens in the `RUN pip install -r python/requirements.txt -r acapy/requirements-latest.txt` in `Dockerfile.acapy`, and thus seems related to a change of behavior in pip version `22.0.4`. With the previous `21.2.4` version, the error is reported, but the build carries on.

We are yet unsure how to fix the problem, but wanted to report it nonetheless.

Build Error:
```
Agents to build: acapy
Backchannel Folder: aries-backchannels/acapy
Building acapy-agent-backchannel ...
Sending build context to Docker daemon  1.558MB

(...)

  Downloading aries_cloudagent-0.2.0.tar.gz (170 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.2/170.2 KB 5.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mc4f_f4j/aries-cloudagent_0f2521f67ba547fa83608e78fc0b33f3/setup.py", line 30, in <module>
          install_requires=parse_requirements("requirements.txt"),
        File "/tmp/pip-install-mc4f_f4j/aries-cloudagent_0f2521f67ba547fa83608e78fc0b33f3/setup.py", line 17, in parse_requirements
          lineiter = (line.strip() for line in open(filename))
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
The command '/bin/sh -c pip install -r python/requirements.txt -r acapy/requirements-latest.txt' returned a non-zero code: 1
Docker image build failed.
```

**Comment by swcurran** [comment]
Thanks for the update. We are much more focused on the `acapy-main` backchannel vs. `acapy`, which is how we missed this. I suspect the problem is with the requirements-latest.txt, but not certain.

@nodlesh @andrewwhitehead -- any ideas?

Perhaps the Dockerfile should be more in line with this? https://github.com/bcgov/aries-cloudagent-container/blob/main/python/Dockerfile

However, that would need to be updated for each ACA-Py release (vs. getting latest release). But maybe that's OK?

**Comment by andrewwhitehead** [comment]
I think that the updated `pip` is ignoring packages that it would previously select, counting backwards until it gets to 0.2.0 here (which fails to install).

**Comment by swcurran** [comment]
Is there a fix?  Lock to the old version of pip?  But that seems wrong...  :-)

**Comment by andrewwhitehead** [comment]
I think it might be a conflict between `aiohttp` selected in python/requirements.txt and in the `aries-cloudagent` package requirements. Changing the install command to split up the two seems to fix the issue: `pip install -r python/requirements.txt && pip install -r acapy/requirements-latest.txt`

**Comment by pruneau628** [comment]
Thanks @andrewwhitehead, docker build now goes through.

**Comment by pruneau628** [comment]
I did run this test:
`./manage rebuild -a acapy` with:
- config A: the current not split `pip install` and the previous version of `python:3.7-slim`
- config B: the split `pip install` and the previous version of `python:3.7-slim`
- config C: the split `pip install` and the latest/current version of `python:3.7-slim`

I tagged the 6 docker produced docker images appropriately and then did a `pip freeze` in the three resulting `aries-test-harness` and `acapy-agent-backchannel` containers:
Of course, the resulting freeze file is the same for all `aries-test-harness` images.
But for `acapy-agent-backchannel`, the resulting pip freeze _added_ 4 new packages for config B & C, from the 59 listed by config A:
```
aiosignal==1.2.0
asynctest==0.13.0
charset-normalizer==2.0.12
frozenlist==1.3.0
```
I do not think it's a problem: I will run some AATH test combinations tomorrow, and if everybody agree I will submit a PR with @andrewwhitehead suggestion,

**Comment by swcurran** [comment]
Please do!

**Comment by pruneau628** [comment]
Hello, I was attempting some kind of A/B testing, in order to make sure that splitting the pip install did not introduce problems, but I ran into a few hurdles:
With commit 684823976f3ecbf8c51898780ed12e876325c24e of the main branch, aka [config A](https://github.com/hyperledger/aries-agent-test-harness/issues/454#issuecomment-1075689394), `./manage rebuild -a acapy` works, but produces a non fonctionnal `acapy-agent-backchannel`:
```
Traceback (most recent call last):
  File "acapy/acapy_backchannel.py", line 22, in <module>
    from python.agent_backchannel import (
  File "/aries-backchannels/python/agent_backchannel.py", line 12, in <module>
    from aiohttp.typedefs import Handler
ImportError: cannot import name 'Handler' from 'aiohttp.typedefs' (/usr/local/lib/python3.7/site-packages/aiohttp/typedefs.py)
~/dev/github/hyperledger/aries-agent-test-harness
```
Since everything seems to revolve around pip dependency resolution, I decided to modify  `aries-backchannels/python/requirements.txt` by changing the line `aiohttp` to `aiohttp>=3.8.1`. This version comes from the pip freeze output of the same container build using  [config C](https://github.com/hyperledger/aries-agent-test-harness/issues/454#issuecomment-1075689394).

Well it's a good thing that pip got upgraded, because after 17 hours, the `pip install` is still going on with pip `version 21.2.4`. They are probably more explanations in https://github.com/pypa/pip/issues/9187.
So what I'm planning to do is just to test [config C](https://github.com/hyperledger/aries-agent-test-harness/issues/454#issuecomment-1075689394), with:
```bash
./manage run -d acapy
./manage run -d acapy -b acapy-main
./manage run -d acapy -b javascript
```
Please note that with the new pip version 22.0.4, the dependency resolution is _much_faster_, as it should be.

If anybody have better ideas for regressiont test, suggestion are welcome.

**Comment by pruneau628** [comment]
So with this commit on the main branch: 684823976f3ecbf8c51898780ed12e876325c24e and using [this solution](https://github.com/hyperledger/aries-agent-test-harness/issues/454#issuecomment-1075629155) I can tell that those two files:
- aries-agent-test-harness/aries-backchannels/acapy/requirements-latest.txt
- aries-agent-test-harness/aries-backchannels/python/requirements.txt
Contains conflicting requirements, as clearly explained by pip:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aries-cloudagent 0.7.3 requires aiohttp~=3.7.4, but you have aiohttp 3.8.1 which is incompatible.
aries-cloudagent 0.7.3 requires async-timeout~=3.0.1, but you have async-timeout 4.0.2 which is incompatible.
```
AFAIK, to solve this issue, the agent and the backchannel should be installed in two independant python virtual environnments.
Now, I'm not really clear on what is the difference between `-a acapy` `-a acapy-main`

**Comment by andrewwhitehead** [comment]
The requirements should be loosened up for ACA-Py, or just the minimum increased, because it has no problems with aiohttp 3.8.x.

`-a acapy` is the last official release while `-a acapy-main` uses the main branch from git.

**Comment by pruneau628** [comment]
Hello, after modifying the requirement files and reversing the `pip install` order in the docker file, I got the correct version of aiohttp and another dependency to be installed in the container image.

After this, I run the following script, in order to help assess possible regressions:
```bash
#! /usr/bin/env bash
date
export LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io
export TAILS_SERVER_URL_CONFIG=https://tails.vonx.io
time ./manage run -d acapy
time ./manage run -d acapy
time ./manage run -d acapy
time ./manage run -d acapy -b acapy-main
time ./manage run -d acapy -b acapy-main
time ./manage run -d acapy -b acapy-main
time ./manage run -d acapy -b javascript
time ./manage run -d acapy -b javascript
time ./manage run -d acapy -b javascript
date
```
The test results where consistents accross the runs:
```
-d acapy:
[run-test.txt](https://github.com/hyperledger/aries-agent-test-harness/files/8380833/run-test.txt)

0 features passed, 13 failed, 0 skipped
83 scenarios passed, 56 failed, 0 skipped
945 steps passed, 36 failed, 143 skipped, 90 undefined
~ 46 min to run
```
```
-d acapy -b acapy-main
0 features passed, 13 failed, 0 skipped
83 scenarios passed, 56 failed, 0 skipped
945 steps passed, 36 failed, 143 skipped, 90 undefined
~ 46 min to run
```
```
-d acapy -b javascript
0 features passed, 13 failed, 0 skipped
44 scenarios passed, 95 failed, 0 skipped
640 steps passed, 92 failed, 392 skipped, 90 undefined
~ 33 min to run
```
Full log is attached to this post [run-test.txt](https://github.com/hyperledger/aries-agent-test-harness/files/8380839/run-test.txt).
I do not have enough historical knowledge on the project to know wether this is really good or bad.
If I have consensus, I'll move [PR 458](https://github.com/hyperledger/aries-agent-test-harness/pull/458) from draft to ready.

**Comment by FrolovVyacheslav** [comment]
```pip install -r python/requirements.txt && pip install -r acapy/requirements-latest.txt``` in Dockerfile.acapy solves this problem

**Comment by pruneau628** [comment]
Indeed, have a look at https://github.com/hyperledger/aries-agent-test-harness/pull/458/commits/6977e9ee7fab7abe5292c5ad892ce76c44567a03

**Comment by nodlesh** [comment]
Are there any remaining issues from this ticket, or can we close it?

**Comment by pruneau628** [comment]
Related PR has been merged, closing.
Thanks for the reminder.
