### ISSUE TITLE
Latest Findy-Javascript tests are broken

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#455]
We're getting all 17 test failing. A quick triage shows the first step of establishing the Acme-Bob connection is failing, per https://allure.vonx.io/api/allure-docker-service/projects/findy-b-javascript/reports/156/index.html

Could someone on the teams (@lauravuo-techlab @TimoGlastra ) take a look at point fingers to get the problem addressed?

Thanks!

**Comment by swcurran** [comment]
Note -- is been failing since March 21.

**Comment by TimoGlastra** [comment]
Will take a look!

**Comment by TimoGlastra** [comment]
It's seems that it is erroring with a 404 when Alice (Findy) wants to send a trust ping to Bob (AFJ).

Do you know why it can't find the connection @lauravuo-techlab?

**Comment by lauravuo-techlab** [comment]
I'll take a look!

**Comment by lauravuo-techlab** [comment]
It seems this was due to our latest refactoring efforts. The fix will be included to next release. Thanks for the heads-up 👍

**Comment by lauravuo-techlab** [comment]
Fixed with findy-agent release 0.30.7: https://allure.vonx.io/api/allure-docker-service/projects/findy-b-javascript/reports/166/index.html @swcurran This can be closed now.

**Comment by swcurran** [comment]
Nice!
