### ISSUE TITLE
issue in aca-py configuration in recent afgo-b-acapy tests

### ISSUE THREAD

**Issue by Moopli** [ianco/aries-agent-test-harness#456]
ACA-Py is configured to auto-accept, so it doesn't produce a problem report for a [didexchange exception test](https://allure.vonx.io/api/allure-docker-service/projects/afgo-b-acapy/reports/latest/index.html?redirect=false#behaviors/b42ec1e2628bcda077660120786966a4/865c2ca749632e9b/).

**Comment by swcurran** [comment]
@nodlesh or @ianco -- can you look?  Thanks!

**Comment by nodlesh** [comment]
We are working on removing that auto option in ACA-Py. It shouldn't be on by default.

**Comment by nodlesh** [comment]
The conversation [here](https://github.com/hyperledger/aries-agent-test-harness/pull/448/files#r835644848) is directly related to this.

**Comment by nodlesh** [comment]
I'm assuming all we need to do here is to remove the auto option that remains in the ACA-Py backchannel?

**Comment by nodlesh** [comment]
Closing since #549 has been merged.
