### ISSUE TITLE
Proposal to fix intermittent fails of tests: Add action to run all runset actions and remove cron triggers

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#457]
We continue to get intermittent test runs being cancelled.  Since the same tests pass one day, cancelled the next and run to completion the day after, it seems likely the problem is one of resource usage -- we have too many tests running in parallel, despite attempts to spread out the tests.

I'm wondering if someone with a depth in GitHub experience could create a job that triggers sequential runs of multiple other jobs to see if that is a viable solution.  If that works we would have each of the runsets Actions (e.g. [test-harness-acapy-afgo.yml](https://github.com/hyperledger/aries-agent-test-harness/blob/main/.github/workflows/test-harness-acapy-afgo.yml)) changed to remove the cron (e.g. manually triggered only).  Then we would have one job that sequentually triggers all of the Actions, plus the "generate results" action.  It means having to keep the names of the actions both as files and listed in the "Run Everything" Action, but that would be easier to manage then the current cron settings on each job.

@WadeBarnes -- if you could try starting on this -- e.g. investigate how to trigger Actions in sequence from an Action -- I can do the rest of the updates to put everything in place (which admittedly is pretty easy :-) ). 

FYI @nodlesh 

Thanks!

**Comment by WadeBarnes** [comment]
I'll have a look.

**Comment by WadeBarnes** [comment]
The initial attempts failed, I ran into a limitation on the number of reusable workflows you can call from your main workflow, and the calling depth when trying to work around that limitation.  Though I have another idea.

**Comment by WadeBarnes** [comment]
Forcing the jobs to run sequentially does not work around the workflow reference limit either.

**Comment by swcurran** [comment]
Could you share what you are trying?  I found a couple of things that suggested approaches, but my understanding of GHAs is not good enough?

**Comment by WadeBarnes** [comment]
See the runs here; https://github.com/WadeBarnes/aries-agent-test-harness/actions

**Comment by WadeBarnes** [comment]
Current iteration looks like this.; https://github.com/WadeBarnes/aries-agent-test-harness/blob/feature/test-control/.github/workflows/run-tests.yml.  I was looking for something that could be done fast with minimal changes to prove out the resource theory.

**Comment by WadeBarnes** [comment]
There is a slightly more complicated from of the same thing I can try that might work.

**Comment by swcurran** [comment]
OK -- looks good, if it works :-).  That's about what I was expecting, but I've never figured out the workflow for testing GHAs -- other than PR, merge and hope, which is a pretty lousy workflow :-).  Thanks for working on this!

**Comment by WadeBarnes** [comment]
I have something running now.  Going to leave it and see how far it gets.
- https://github.com/WadeBarnes/aries-agent-test-harness/runs/5729935533?check_suite_focus=true
- https://github.com/WadeBarnes/aries-agent-test-harness/blob/1f9002d685acde279be5eb2b47ad2e05a5c4aceb/.github/workflows/run-tests.yml

One downside, due to the way the test workflows are being triggered the main workflow is only able to pick them up from the `main` branch, it will not run the versions off a different branch.

**Comment by WadeBarnes** [comment]
The action I was using for the run above ended up hanging when one of the tests failed, and it was difficult to get the workflow to stop afterward.

I'm trying out the different action that seems more responsive and provides better feedback, here:
- https://github.com/WadeBarnes/aries-agent-test-harness/blob/908219d68ebf8093120eed6135ad3f1902d52a1d/.github/workflows/run-tests-2.yml
- https://github.com/WadeBarnes/aries-agent-test-harness/runs/5739665188?check_suite_focus=true

**Comment by WadeBarnes** [comment]
I've tried two different GitHub Actions to trigger the test workflows from a main controlling workflow, however the main workflow ends up hanging (being cancelled) before it completes all of the tests.
- Yesterday; https://github.com/WadeBarnes/aries-agent-test-harness/runs/5730035016?check_suite_focus=true
- Today; https://github.com/WadeBarnes/aries-agent-test-harness/runs/5739665188?check_suite_focus=true

Both have hung a test apart just over the half way mark.  They are being canceled for exceeding the maximum execution time of 360 minutes.  Which is simply a function of how long the tests are taking to run.

I'll need to look into running some of the tests in parallel to reduce the execution time.

The other option is to daisy chain the tests together where the end of one test workflow would trigger the execution of the next test workflow.  This would keep the sequential execution of the test and avoid the 360 minute time limit, however it becomes a maintenance issue in that each test needs to be somewhat aware of what test is next in the sequence so it can trigger it.

**Comment by WadeBarnes** [comment]
Trying out a throttled matrix strategy that limits the number of concurrent running test workflows:
- https://github.com/WadeBarnes/aries-agent-test-harness/blob/c9ccd8747fce29de763ddee3601b171ad07acc2d/.github/workflows/run-tests-3.yml
- https://github.com/WadeBarnes/aries-agent-test-harness/actions/runs/2061433867

As tests complete new test runs should be started.  Generate summary results has been configured as it's own dependent job that will wait for the tests to complete.

**Comment by WadeBarnes** [comment]
Added dynamic test harness lookup:
- https://github.com/WadeBarnes/aries-agent-test-harness/blob/9c67260b8fbe15b0de2fc154b167a9dd9075ffc0/.github/workflows/run-tests-3.yml
- https://github.com/WadeBarnes/aries-agent-test-harness/actions/runs/2061629858

The test harness runs will always fail when run in my repo because I don't have the Allure upload credentials configured as I don't want to pollute the results with the testing.

**Comment by swcurran** [comment]
Awesome work on this!
