### ISSUE TITLE
ACA-Py / AFJ Tests are failing

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#471]
19 of the tests are suddenly failing -- not sure what the issue(s) is(are). For example - Acme is ACA-Py

```
AssertionError: FAILED SUB-STEP: When "Acme" creates a new schema Substep info: Assertion Failed: resp_status 500 is not 200; Extra data: line 1 column 4 (char 3) Traceback (of failed substep): File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run match.run(runner.context) File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run self.func(context, *args, **kwargs) File "features/steps/0036-issue-credential.py", line 86, in step_impl assert resp_status == 200, f"resp_status {resp_status} is not 200; {resp_text}"
```

See this page for the full list of errors: https://allure.vonx.io/api/allure-docker-service/projects/acapy-b-javascript/reports/416/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

@ianco -- can you please take a first look at this one?

**Comment by nodlesh** [comment]
This also happens in acapy-acapy tests as well.

**Comment by TimoGlastra** [comment]
This is an issue in ACA-Py that arose from this PR: https://github.com/hyperledger/aries-cloudagent-python/pull/1721, and fixed by this PR: https://github.com/hyperledger/aries-agent-test-harness/pull/473
