### ISSUE TITLE
Refactor Docker env handling in manage script

### ISSUE THREAD

**Issue by nodlesh** [ianco/aries-agent-test-harness#483]
Following the pattern set in https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/run_demo#L193
refactor the setting and passing the environment to the docker run commands in the manage script for AATH. 

Also need the env var START_TIMEOUT added for acapy.

**Comment by harris2310** [comment]
Hello there, I could try to resolve this for you

**Comment by nodlesh** [comment]
I'm working on this since I need to refactor the agent start commands to properly support taking GENESIS_URL.
