### ISSUE TITLE
afgo-interop test agent not building

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#493]
The afgo-interop test agent is not building. @Moopli -- are you able to help with this?  The afgo agent is still building.

I think the GO_VER and ALPINE_VER also need to be updated to `1.17` and `3.15` respectively.

It's getting the following error:

```
.
.
.
Step 15/38 : RUN GO_TAGS=${GO_TAGS} GOPROXY=${GOPROXY} make agent-rest-acapy-interop
 ---> Running in 60ca0ab4cfec
Building aries-agent-rest for aca-py interop
.
.
.
go: downloading github.com/tidwall/match v1.0.3
go: downloading github.com/tidwall/pretty v1.0.2
# github.com/hyperledger/aries-framework-go/pkg/doc/did
../../pkg/doc/did/serialize_interop.go:68:32: services[i].RoutingKeys undefined (type Service has no field or method RoutingKeys)
make: *** [Makefile:131: agent-rest-acapy-interop] Error 2
The command '/bin/sh -c GO_TAGS=${GO_TAGS} GOPROXY=${GOPROXY} make agent-rest-acapy-interop' returned a non-zero code: 2
Docker image build failed.
~/repos/aries-agent-test-harness [main !] 11:57 $ 
```

**Comment by baha-ai** [comment]
this should be fixed when this PR is merged: https://github.com/hyperledger/aries-framework-go/pull/3239

thanks for raising the issue.

**Comment by swcurran** [comment]
This is now fixed, but none of the tests are currently passing between ACA-Py and AF-Go.  I'll open a new issue with the details.
