### ISSUE TITLE
As a user, I would expect the left column of the aries-interop website to be sorted

### ISSUE THREAD

**Issue by ryjones** [ianco/aries-agent-test-harness#498]
https://aries-interop.info/ has the Introduction sorted at the bottom of the list.

<img width="298" alt="Screen Shot 2022-05-17 at 4 09 57 PM" src="https://user-images.githubusercontent.com/466142/168926785-df53e337-a3bb-45d1-b8f6-db94d560bb19.png">

I would like it to be sorted

**Comment by harris2310** [comment]
Hello there, I could resolve this for you

**Comment by swcurran** [comment]
Might be trickier than you expect. The docs are generated from a script `gen-interop.sh` in the root folder.  I just need a way to float the "Introduction" doc to the top alphabetically, and I didn't come up with a way to do that.  The hack of the "1. " at the beginning at least floated it to the bottom :-). 

If someone has a suggestion to force the sort order, let me know. I can easily make the change in the shell script.

**Comment by swcurran** [comment]
Looked again and I can't see an easy way to do this.  Preference would be to use a different theme -- updating to something that is maintained.

Closing this.
