### ISSUE TITLE
ACA-Py DIDComm V2 service endpoint not an array

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#509]
Per this comment in another issue: https://github.com/hyperledger/aries-agent-test-harness/issues/502#issuecomment-1148920667, the  implementation of DIDComm V2 is not an array and should be.  Per a follow up comment, the issue in the `pydid`.

A manifestation of the problem can be created using these steps:

- use Aries Agent Test Harness
- `./manage build -a acapy-main -a afgo-interop`
- `./manage service start orb`
- `./manage run -d acapy-main -b afgo-interop -v 20 -t @T005-RFC0023`
- ./manage service stop orb` # For cleanup

The one test will fail because of this issue.

Please take a look @dbluhm .

**Comment by TheTechmage** [comment]
Internally, @dbluhm has assigned this to me. When I attempt to follow the above steps, I get the following error when it is attempting to setup a local von-network:
```
ERROR: pull access denied for von-network-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by swcurran** [comment]
I assume that is happening on the `./manage run` step?

To get around it, you can start a "normal" von-network on your system -- hopefully you are familiar with that.

The error appears to be that you need to be logged into docker hub by doing a "docker login" at the command line.  Once your credentials are setup, you should be good to go.

**Comment by TheTechmage** [comment]
I am logged in to dockerhub but I am still seeing the mentioned error. I'll look into what it takes to start a normal von network, then launch the test here using that network.

**Comment by swcurran** [comment]
Basically, just git clone the von-network repo (https://github.com/bcgov/von-network), cd into it the repo and execute `./manage build; ./manage start`

On the other hand, that's exactly what is happening in AATH, so you may still have a problem.

**Comment by nodlesh** [comment]
You can also use the LEDGER_URL_CONFIG environment variable to point to a running von network.

**Comment by TheTechmage** [comment]
PR submitted here https://github.com/dbluhm/pydid/pull/51. Working with @dbluhm to get it merged in.

**Comment by TheTechmage** [comment]
It had been merged in and a release was made on Friday. This should be fixed now

**Comment by swcurran** [comment]
Looks good!  Tested locally and the test passed. Thanks!

**Comment by 2byrds** [comment]
> Basically, just git clone the von-network repo (https://github.com/bcgov/von-network), cd into it the repo and execute `./manage build; ./manage start`
> 
> On the other hand, that's exactly what is happening in AATH, so you may still have a problem.

This got me going with AATH.  I had zero indy ledger experience and saw in the AATH README that I needed a running ledger.  @swcurran instructions made it super easy to get a von-network running so that I could start running tests.  Consider adding this small instruction as a suggestion in the README.

**Comment by swcurran** [comment]
Hey @2byrds -- not sure what is needed in the README. Could you expand a bit?

Normally, when you run AATH locally, it will automagically start up the ledger (and a tails server), run the tests, and the stop the ledger (and tails service).  Did you not see that?  Or did you think you needed the ledger and so started it using von-network yourself?

Also, to start up the ledger and then do a bunch of runs, you can run this command:

`./manage service start von-network; ./manage service start indy-tails; ./manage service start uniresolver`

and later, after you are done all the `./manage run...` commands, you can:

`./manage service stop von-network; ./manage service stop indy-tails; ./manage service stop uniresolver`

And, for full disclosure -- if you are running AF-Go tests that use the `did:orb`, there is a `./manage service start orb` and equivalent `stop` command.
