### ISSUE TITLE
Add mediator tests when establishing connections use DID Exchange (RFC0023)

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#523]
We have a number of tests that cover various Mediator scenarios (tagged RFC0211), however all of those establish connections using the RFC0160 Connections Protocol. We need to add some tests that test mediation with DID Exchange.

**Comment by nodlesh** [comment]
Is there still something to achieve here given the mediation tests with DID Exchange as documented here?  https://github.com/hyperledger/aries-agent-test-harness/blob/main/aries-test-harness/features/0211-coordinate-mediation.feature#L7-L26

**Comment by nodlesh** [comment]
I believe this can be closed based on the existing tests mentioned above.
