### ISSUE TITLE
Notice in GitHub action about using a deprecated feature -- set output

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#581]
I was investigating the an error in the running of some workflows and saw this in the GitHub Action logs -- I think from the "runner" action.  Came from the acapy-aip10 job on Oct. 20, 2022.

Should I be concerned about this @WadeBarnes ?

```
The workflow logs can be found at https://github.com/hyperledger/aries-agent-test-harness/actions/runs/3293902858
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/[20](https://github.com/hyperledger/aries-agent-test-harness/actions/runs/3293879234/jobs/5430821305#step:3:21)22-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by swcurran** [comment]
Here is the URL to the logs: https://github.com/hyperledger/aries-agent-test-harness/actions/runs/3293879234/jobs/5430821305

**Comment by WadeBarnes** [comment]
GitHub Action runners are being updated.  There are two main deprecation warnings ATM.  One for the `set-output` syntax and one for the deprecation of Node.js 12 runners (they are moving to Node.js 16).  @pSchlarb and I are in the process of updating the Indy workflows.

To fix the `set-output` warning you need to update to the newer syntax.  An example can be found here; https://github.com/hyperledger/indy-shared-gha/compare/a320758da208197cb37c7b7e3a00be7e66df0090...17064996905981f9b3307765d30f904928b280b2#diff-9d5a866e39d6936c0ac08483f622a977dd5e42d66515ef46a9d2e0ff06c6a75bL63-R68

To fix the Node.js 12 warning you need to update to a newer version of the identified actions that have added support for the Node.js 16 runners.  For example https://github.com/hyperledger/indy-shared-gha/compare/a320758da208197cb37c7b7e3a00be7e66df0090...17064996905981f9b3307765d30f904928b280b2#diff-cd8ed0df557a4aaa5f7e18621af05507027fd4e362814e3738b5cc504424a45aL65-R65

**Comment by WadeBarnes** [comment]
The following PRs have been submitted to address this issue:
- https://github.com/hyperledger/aries-agent-test-harness/pull/620
- https://github.com/hyperledger/aries-agent-test-harness/pull/631

There is one action outstanding, `the-coding-turtle/ga-file-list@v0.4.1`, which does not have a fix yet.  I've submitted an issue; https://github.com/the-coding-turtle/ga-file-list/issues/92.  We'll upgrade when there is a new release.
