### ISSUE TITLE
All test runners are failing with an error 401 "Bad Credentials"

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#619]
All of the GHA-triggered runsets are failing with the following error.

@WadeBarnes can you please take a look?  Could this be related to the token issue that @ryjones mentioned on Discord the other day about his token being deactivated?

Thanks

```
curl: (22) The requested URL returned error: 401
api failed:
path: workflows/test-harness-acapy-afgo.yml/runs?event=workflow_dispatch&created=>=2022-[12](https://github.com/hyperledger/aries-agent-test-harness/actions/runs/3666574620/jobs/6198390524#step:3:13)-11T00:19:48+00:00&actor=&per_page=100
response: {
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
Triggering workflow:
  workflows/test-harness-acapy-afgo.yml/dispatches
  {"ref":"main","inputs":{}}
curl: (22) The requested URL returned error: 401
api failed:
path: workflows/test-harness-acapy-afgo.yml/dispatches
response: {
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```

**Comment by WadeBarnes** [comment]
The `REPO_ACCESS_TOKEN` needs to be updated.  I've messaged @ryjones.  Original request (when this was first setup) is here; https://github.com/hyperledger/aries-agent-test-harness/pull/459#issuecomment-1083462832

**Comment by WadeBarnes** [comment]
@ryjones has updated the `REPO_ACCESS_TOKEN`, and the test-runner is working again.

**Comment by WadeBarnes** [comment]
@ryjones, It looks like the `REPO_ACCESS_TOKEN` has expired again.

**Comment by ryjones** [comment]
updated
