### ISSUE TITLE
Please use Apache-2 license

### ISSUE THREAD

**Issue by ryjones** [ianco/aries-agent-test-harness#642]
[Please see this report](https://lfscanning.org/reports/hyperledger/aries-2022-12-31-bb1faa14-5ed8-4ede-97d8-11cf9ad61f77.html)

https://github.com/hyperledger/aries-agent-test-harness/blob/a463137ca9ac026d954cd9f62a6cf297b8602fc4/aries-backchannels/verity/package.json#L21

**Comment by swcurran** [comment]
We will be shortly removing the Verity backchannel from the repo.  Is that sufficient or should the file be corrected before deletion?

**Comment by swcurran** [comment]
This has been addressed through the removal of the Verity backchannel.  Closing.
