### ISSUE TITLE
Ability to Retry a Failed test in a test run

### ISSUE THREAD

**Issue by nodlesh** [ianco/aries-agent-test-harness#646]
This enhancement will allow for test retries on failed tests. Can set to any number of retries, but is defaulted to no retries (1). 

Follow the same implementation done for AMTH here, https://github.com/hyperledger/aries-mobile-test-harness/pull/134
and the fix for the manage script here, https://github.com/hyperledger/aries-mobile-test-harness/pull/135

**Comment by ggold7046** [comment]
Hi, I'm looking for some hyperledger test issues. Could you please guide me on how to find one ?
