### ISSUE TITLE
Test runs are failing on GHA -- please investigate

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#657]
See the latest result: https://github.com/hyperledger/aries-agent-test-harness/actions/runs/4432199000

The problem started yesterday.  

- Several notices are about "commands are deprecated" -- Node.js 12, set-output.
- Docker Build Failed on dotnet -- perhaps it is time to remove the dotnet test agent?
- **The key error though is a "Bad Credentials" message when running the test harnesses.**

Please investigate.

**Comment by nodlesh** [comment]
Last time a run was successful and results pushed to allure was March 11th. So this issue started on the 12th I think.

**Comment by WadeBarnes** [comment]
It looks like the REPO_ACCESS_TOKEN has expired again.  Issue reported here; https://github.com/hyperledger/aries-agent-test-harness/issues/619#issuecomment-1472376377

**Comment by ryjones** [comment]
updated token

**Comment by swcurran** [comment]
Thanks - will monitor tonight’s run.

**Comment by WadeBarnes** [comment]
All the tests ran and passed.  The test harness runner times out on three of the runs because they took over an hour to run, although they did end up completing and passing.  Updating the token has resolved the reported issue.

Thanks @ryjones
