### ISSUE TITLE
ACA-Py Build is failing

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#697]
The ACA-Py build is failing as of a few days ago. The error log contains:

```
.
.
.
E: Unable to locate package libindy
E: Unable to locate package libnullpay
The command '/bin/sh -c apt-get update    && apt-get install -y git gnupg2 software-properties-common curl    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88    && add-apt-repository 'deb https://repo.sovrin.org/sdk/deb bionic stable'    && apt-get update    && apt-get install -y libindy libnullpay' returned a non-zero code: 100
Docker image build failed.
Error: Process completed with exit code 1.
Run /home/runner/work/aries-agent-test-harness/aries-agent-test-harness/./test-harness/actions/run-test-harness-wo-reports/store-failed-env.sh -d acapy-main
Run jwalton/gh-docker-logs@v2
Found 8 containers...
```

**Comment by usingtechnology** [comment]
Appears to be an issue with where we get `libindy` and `libnullindy`. 

I did try various different settings for the https://repo.sovrin.org/sdk/deb repo  - (`xenial`, `bionic`, `master`, `rc`, `stable`) and no difference.

I don't know how apt-get resolves to https://repo.sovrin.org/sdk/lib/apt/bionic/stable/ but those libindy/libnullpay libraries are not resolving. If I remove them from the images, it builds (obviously won't run).

If I do a package search (ex `apt search --names-only ^libind` or `apt search --names-only ^libnu`) the packages we want are not found.

**Comment by nodlesh** [comment]
I've been working on this as well for a couple of days. Can't seem to get `apt-get` to work with these packages.
I've also have been trying to use a different base like indy-base, 
`FROM ghcr.io/findy-network/findy-base:indy-1.16.ubuntu-18.04 AS indy-base` and copying those libs. 
```
COPY --from=indy-base /usr/include/indy /usr/include/indy
COPY --from=indy-base /usr/lib/libindy.a /usr/lib/libindy.a
COPY --from=indy-base /usr/lib/libindy.so /usr/lib/libindy.so
```
but I'm having other issue with that when it is building.

**Comment by nodlesh** [comment]
Have a fix for this thanks to Clecio. Will do a PR after I make sure everything runs.

**Comment by WadeBarnes** [comment]
I was just about to submit a PR.  The fix is to switch to `python:3.7-slim-bullseye` as the base image.  `python:3.7-slim` is now based on `bookworm`.  The change was made 4 days ago.

**Comment by nodlesh** [comment]
If you have it ready then go ahead. Could do `python:3.7-slim-buster` as well to keep inline with the rest of the containers in the test harness.

**Comment by WadeBarnes** [comment]
Will do.  `buster` is older.  The other images should be updated to use `bullseye`, but I'll leave that for now.
