### ISSUE TITLE
von-webserver-1 missing dependency

### ISSUE THREAD

**Issue by anonyomax** [ianco/aries-agent-test-harness#711]
Hi, this version of the von-webserver results in the following error in the docker logs:
`Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/server/server.py", line 14, in <module>
    from .anchor import (
  File "/home/indy/server/anchor.py", line 15, in <module>
    import nacl.signing
ModuleNotFoundError: No module named 'nacl'`

This is after a successful build and running:
`./manage run -a acapy -b acapy -f acapy -m acapy`

which results in:
```
 ✔ Network von_von                                                                                                                                          Created0.0s inux/amd64) does not match the detected host platform (linux/arm64/v8) and no specif
 ✔ Container von-node1-1                                                                                                                                    Started1.0s inux/amd64) does not match the detected host platform (linux/arm64/v8) and no specif
 ✔ Container von-node2-1                                                                                                                                    Started0.8s inux/amd64) does not match the detected host platform (linux/arm64/v8) and no specif
 ✔ Container von-node3-1                                                                                                                                    Started0.9s inux/amd64) does not match the detected host platform (linux/arm64/v8) and no specif
 ✔ Container von-webserver-1                                                                                                                                Started0.9s m (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no sp
 ✔ Container von-node4-1                                                                                                                                    Started0.9s 
 ! node2 The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested     0.0s 
 ! node1 The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested     0.0s 
 ! node4 The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested     0.0s 
 ! node3 The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested     0.0s 
 ! webserver The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
Want to see the scrolling container logs? Run "./manage logs"
waiting for ledger to start/respond..........................................................\e[31m
The Indy Ledger failed to start within 60 seconds.
\e[0m

\e[31m
The Indy Ledger is not running.
\e[0m 
```

**Comment by WadeBarnes** [comment]
It appears you're running on an arm based MAC.  Try running `export DOCKER_DEFAULT_PLATFORM=linux/amd64` on the command line and then run the build followed by `./manage run -a acapy -b acapy -f acapy -m acapy`.

**Comment by anonyomax** [comment]
Thank you for your response, yes I am running it on an ARM based Mac so i will be using 
`DOCKER_DEFAULT_PLATFORM=arm64` from now on. That does resolve the warning messages however the von-webserver image still cannot resolve the `pynacl` dependency:
![image](https://github.com/hyperledger/aries-agent-test-harness/assets/139839470/9651fa4d-e664-4b39-838b-a02c5652eb66)

**Comment by WadeBarnes** [comment]
You want to use `export DOCKER_DEFAULT_PLATFORM=linux/amd64` not `DOCKER_DEFAULT_PLATFORM=arm64`.  You my also need to rebuild von-network.  See this comment in a related issue; https://github.com/hyperledger/aries-agent-test-harness/issues/710#issuecomment-1640242417
