### ISSUE TITLE
All AATH workflows are failing to run due to Bad Creds

### ISSUE THREAD

**Issue by nodlesh** [ianco/aries-agent-test-harness#756]
All workflows are failing as seen here, https://github.com/hyperledger/aries-agent-test-harness/actions/runs/7360755836/job/20037268563#step:3:13

The REPO_ACCESS_TOKEN used here,https://github.com/hyperledger/aries-agent-test-harness/actions/runs/7360755836/workflow#L70, has expired.

We need an updated Token. @ryjones I think you are managing those?

**Comment by ryjones** [comment]
I think this is fixed, after working with @WadeBarnes
